### PR TITLE
added hyprland support

### PR DESCRIPTION
**Pull request by eylles**
@Magnitudexx

### CODE REVIEW

**Comment by eylles** [comment]
@vaxerski is this okay?

or should it be done differently?

**Comment by vaxerski** [comment]
wat?

**Comment by eylles** [comment]
the idea that the commit proposes of 
"consider hyprland a desktop, run hyprpaper if it is present"

is it okay or is it dumb? i will be honest chief, i don't use hyprland but i do get requests of supporting more wayland software in pywal16, and the commit isn't mine but something i found on github and like a hungry vulture i snatched and gobbled said commit into my repo to create a PR.

**Comment by vaxerski** [comment]
I mean hyprpaper will run hyprpaper but you need a config for it to work

**Comment by eylles** [comment]
so, unless the user is explicitly configuring hyprpaper to use whatever image pywal sets as wallpaper, it will not work, right?

on my setup (awesome wm) i do need to have the full path to whatever wallpaper i'm using (pywal kinda cheats on that regard as what it does with awesome will not stick between reloads) so among all the cheats and hacks i take the path of least resistance which is using a symlink to whatever image in a static location:
```sh
##########################################
# this is a snippet from a larger script #
##########################################

bgloc="${XDG_DATA_HOME:-$HOME/.local/share/}/bg"

# link the image file passed to script
ln -sf "$(readlink -f "$image")" "$bgloc"

# pywal shenanigans happen here
wal --backend "$BackEnd" --cols16 "$colsmethod" -i "$(readlink -f "$bgloc")" -o "${XDG_CONFIG_HOME}"/wal/postrun
```
[full script](https://github.com/eylles/elthemer/blob/master/setbg)

so long as hyprpaper can resolve a symlink like that to the actual image (not every program in linux i've tested that deals with images is robust enough to take an extensionless file, notice it is a symlink, resolve the link and open the actual image tho) i could recommend this sort of method for hyprpaper users that want to use pywal16 and want out of the box integration.

**Comment by vaxerski** [comment]
a symlink should work, why not test it tho

**Comment by eylles** [comment]
If ya say it works then i'll take your word.

**Comment by osamaaj03** [comment]
I wanted to suggest an option for users who don't rely on hyprpaper with hyprland. Previously, pywal worked seamlessly with swaybg, but since the last update, it now requires hyprpaper to be installed and executable, and won't work with other wallpaper setters unless I deleted the two lines from this commit. It would be great if there could be an option to accommodate users who prefer alternative wallpaper setters, allowing them to continue using pywal without having to install hyprpaper. This would provide more flexibility and make pywal more compatible with different setups

**Comment by eylles** [comment]
@osamaaj03 i'm on lunch rn but once i'm home i can take the time to tweak the behavior to try through the different wayland wallpaper setters if hyprpaper is not available with hyprland.

**Pull request merged**
