### PR TITLE
add zed template

### PR DESCRIPTION
**Pull request by nickbuckham**
20240819_19h03m01s_grim
20240819_19h02m35s_grim
20240819_19h02m06s_grim
20240819_19h00m13s_grim
20240819_18h59m58s_grim
20240819_18h58m44s_grim

### CODE REVIEW

**Comment by nickbuckham** [comment]
Feel free to close if it doesn't fit the scope of things you want to provide templates for. I made it for myself and figured I'd leave it here.

Should potentially be renamed to `colors-zed-dark.json` as it doesn't work the best as a light theme. Would be great to eventually generate a "greys" palette similar to tailwind gray-50->gray-950 for things like this as templates are limited to opacity for text shading.

**Comment by eylles** [comment]
I got no prob adding but i'm just curious, wot is this "zed" ya talk about?

**Comment by nickbuckham** [comment]
The program you see in the screenshots :) https://zed.dev/

**Comment by eylles** [comment]
okay, the only sorta program i would oppose to add templates of would be something that is proprietary or that isn't properly free software nor open source, for example i would reject templates for the vivaldi web browser

**Pull request merged**
