### PR TITLE
okthief backend

### PR DESCRIPTION
**Pull request by eylles**
thanks to @cakekindel

i still need to make some adjustments to have the secondary color shades.

just a question the only source right now is this: https://git.orionkindel.com/orion/okthief right? there is no package just installing from source right?

### CODE REVIEW

**Comment by cakekindel** [comment]
I've just published okthief to crates.io, so if you have rust installed on your system you can install from source with `cargo install okthief`.

I also published a release with binaries for linux (x86_64) and windows (x86_64): https://git.orionkindel.com/orion/okthief/releases

There's a 4MB limit to release files on gitea, so I had to upload it as a split 7z. Here's a zip:
[okthief-win-x86_64.zip](https://github.com/eylles/pywal16/files/15407424/okthief-win-x86_64.zip)

**Comment by eylles** [comment]
may be a good idea to have a mirror for the okthief source and not just your personal gitea instance, foe example i've been thinking of mirroring pywal16 to either gitlab or codeberg but have not decided which one yet.

**Comment by eylles** [comment]
@cakekindel can you please test that it works correctly with the --cols16 flag? as in the shades are within expectation?

**Comment by eylles** [comment]
yolo, will assume this works, if it doesn't then the issues will come eventually.

**Pull request merged**
